name: Assume Role in AWS and Run Terraform Init with S3 Backend

on:
  pull_request:
    branches: [ main ]

jobs:
  assume-role-and-run-terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Assume role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-1 

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.10

    - name: Terraform init with S3 backend
      run: terraform init -input=false -backend-config="bucket=${AWS_BUCKET}" -backend-config="key=${AWS_KEY}" -backend-config="region=${AWS_REGION}"

    - name: Terraform plan
      run: |
        terraform plan
