---
name: AWS config && Terraform Plan 
on:
  pull_request:
    branches:
      - "main"

permissions:
  id-token: write
  contents: read

jobs:
  aws-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ARN }}
          aws-region: us-east-1


  terraform-setup:
    needs: aws-config
    runs-on: ubuntu-latest
    steps:
    - name: "set up terraform cli"
      uses: hashicorp/setup-terraform@v2

  tf-init:
    needs: terraform-setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "run terraform init"
      run: terraform init  -backend-config="role_arn=${{ secrets.AWS_ARN }}" -backend-config="bucket=${{ secrets.AWS_BUCKET }}" -backend-config="encrypt=true" -backend-config="key=${{ secrets.AWS_KEY }}" -backend-config="region=${{ secrets.AWS_REGION }}"

  tf-plan:
    needs: tf-init
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "run terraform plan"
      run: terraform plan
