---
name: AWS config && Terraform Plan 
on:
  pull_request:
    branches:
      - "main"

jobs:
  aws-config:
    runs-on: ubuntu-latest
    steps:
      - name: aws creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secret.AWS_ARN}}
          aws-region: us-east-1

  terraform-plan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: "set up terraform cli"
      uses: hashicorp/setup-terraform@v2

    - name: "run terraform init"
      run: terraform init

    - name: "run terraform plan"
      run: terraform plan
